"""
Datafast — all 7 tools as explicit @mcp.tool() functions.

Datafast uses form-encoded POST (not JSON) and a custom fiscal engine
that produces string amounts ("12.50"). All tools live here.
"""

from __future__ import annotations

import json
import re
from typing import Any

from mcp_common.security import validate_safe_url, validate_amount

import server
from _fiscal import TipoMonto, calcular_strings_fiscales
from app import mcp


@mcp.tool()
async def crear_checkout(
    entity_id: str,
    monto: float,
    payment_type: str,
    tipo_monto: TipoMonto = TipoMonto.SUBTOTAL,
    subtotal_iva0: str = "0.00",
    valor_ice: str = "0.00",
    currency: str = "USD",
    merchant_transaction_id: str | None = None,
    customer_email: str | None = None,
    customer_nombre: str | None = None,
    customer_apellido: str | None = None,
    customer_doc_tipo: str | None = None,
    customer_doc_numero: str | None = None,
    billing_calle: str | None = None,
    tokenizar_tarjeta: bool = False,
) -> str:
    """⚠️ MUTATION — Create a Checkout session in Datafast to initiate a card payment — POST /v1/checkouts.

    STEP 1 of the standard Datafast payment flow.

    MONETARY INPUT: pass `monto` verbatim + `tipo_monto` ("subtotal"|"total_con_iva").
    Server computes fiscal strings. Violation causes error 100.400.500.

    REQUIRED PARAMETERS:
      entity_id (str): Commerce entity ID issued by Datafast.
      monto (float): Amount exactly as stated by the user.
      payment_type (str): "DB"=Direct debit/purchase | "PA"=Pre-authorization.

    RETURNS:
      JSON with 'id' (checkoutId) and 'result.code' (success = "000.200.100").
    """
    amount_str, subtotal_gravado_str, valor_iva_str = calcular_strings_fiscales(monto, tipo_monto)
    server.logger.info("[crear_checkout] monto=%.2f tipo=%s → amount=%s subtotal_gravado=%s valor_iva=%s",
        monto, tipo_monto.value, amount_str, subtotal_gravado_str, valor_iva_str)

    data: dict[str, Any] = {
        "entityId": entity_id,
        "amount": amount_str,
        "currency": currency,
        "paymentType": payment_type,
        "customParameters[SHOPPER_VAL_BASE0]": subtotal_iva0,
        "customParameters[SHOPPER_VAL_BASEIMP]": subtotal_gravado_str,
        "customParameters[SHOPPER_VAL_IVA]": valor_iva_str,
        "customParameters[SHOPPER_VAL_ICE]": valor_ice,
    }
    if merchant_transaction_id is not None:
        data["merchantTransactionId"] = merchant_transaction_id
    if customer_email is not None:
        data["customer.email"] = customer_email
    if customer_nombre is not None:
        data["customer.givenName"] = customer_nombre
    if customer_apellido is not None:
        data["customer.surname"] = customer_apellido
    if customer_doc_tipo is not None:
        data["customer.identificationDocType"] = customer_doc_tipo
    if customer_doc_numero is not None:
        data["customer.identificationDocId"] = customer_doc_numero
    if billing_calle is not None:
        data["billing.street1"] = billing_calle
    if tokenizar_tarjeta:
        data["createRegistration"] = "true"

    result = await server._post_form("/v1/checkouts", data)
    return server._json(result)


@mcp.tool()
async def verificar_pago_checkout(entity_id: str, checkout_id: str) -> str:
    """Verify the final status of a Datafast payment — GET /v1/checkouts/{id}/payment.

    STEP 3 of the standard Datafast flow, after the frontend card form completes.

    REQUIRED PARAMETERS:
      entity_id (str): Commerce entity ID.
      checkout_id (str): checkoutId generated by crear_checkout.

    RETURNS:
      JSON with result.code, id (real payment ID for reversals), registrationId if tokenized.
    """
    result = await server._get(f"/v1/checkouts/{checkout_id}/payment", params={"entityId": entity_id})
    return server._json(result)


@mcp.tool()
async def consultar_pago_por_orden(entity_id: str, merchant_transaction_id: str) -> str:
    """Search for a transaction by your internal order number — GET /v1/query.

    REQUIRED PARAMETERS:
      entity_id (str): Commerce entity ID.
      merchant_transaction_id (str): Order number sent as merchant_transaction_id in crear_checkout.

    RETURNS:
      List of matching transactions with result.code, amount, id.
    """
    result = await server._get("/v1/query",
        params={"entityId": entity_id, "merchantTransactionId": merchant_transaction_id})
    return server._json(result)


@mcp.tool()
async def reversar_reembolsar_pago(
    entity_id: str, payment_id: str, amount: str, payment_type: str, currency: str = "USD"
) -> str:
    """⚠️ MUTATION — Reverse or refund a previously approved payment — POST /v1/payments/{id}.

    REQUIRED PARAMETERS:
      entity_id (str): Commerce entity ID.
      payment_id (str): Real payment ID from verificar_pago_checkout (NOT checkoutId).
      amount (str): Amount to reverse/refund, 2 decimal places. Example: "12.50"
      payment_type (str): "RV"=Reversal (same-day void) | "RF"=Refund (post-day).

    RETURNS:
      JSON with result.code and refund confirmation.
    """
    try:
        validate_amount(float(amount), "amount")
    except ValueError as exc:
        raise ValueError(f"amount debe ser un string numérico válido: {exc}") from exc
    result = await server._post_form(f"/v1/payments/{payment_id}",
        {"entityId": entity_id, "amount": amount, "currency": currency, "paymentType": payment_type})
    return server._json(result)


@mcp.tool()
async def pago_recurrente_oneclick(
    entity_id: str,
    registration_id: str,
    amount: str,
    currency: str = "USD",
    payment_type: str = "DB",
    shopper_result_url: str | None = None,
) -> str:
    """⚠️ MUTATION — Charge a tokenized (saved) card — POST /v1/registrations/{id}/payments.

    REQUIRED PARAMETERS:
      entity_id (str): Commerce entity ID.
      registration_id (str): Card token (registrationId) from verificar_pago_checkout.
      amount (str): Amount with 2 decimal places. Example: "99.00"

    OPTIONAL PARAMETERS:
      currency (str, default="USD")
      payment_type (str, default="DB"): "DB"=Direct purchase.
      shopper_result_url (str): Required if 3DS challenge is triggered.

    RETURNS:
      JSON with result.code, transaction id, authorizationCode, card details.
    """
    try:
        validate_amount(float(amount), "amount")
    except ValueError as exc:
        raise ValueError(f"amount debe ser un string numérico válido: {exc}") from exc
    if shopper_result_url is not None:
        shopper_result_url = validate_safe_url(shopper_result_url, "shopper_result_url")
    data: dict[str, Any] = {"entityId": entity_id, "amount": amount, "currency": currency, "paymentType": payment_type}
    if shopper_result_url is not None:
        data["shopperResultUrl"] = shopper_result_url
    result = await server._post_form(f"/v1/registrations/{registration_id}/payments", data)
    return server._json(result)


@mcp.tool()
async def eliminar_token_tarjeta(entity_id: str, registration_id: str) -> str:
    """⚠️ IRREVERSIBLE MUTATION — Delete a saved card token — DELETE /v1/registrations/{id}.

    REQUIRED PARAMETERS:
      entity_id (str): Commerce entity ID.
      registration_id (str): Card token (registrationId) to delete.

    RETURNS:
      JSON confirmation of deletion.
    """
    result = await server._delete_form(f"/v1/registrations/{registration_id}", params={"entityId": entity_id})
    return server._json(result)


@mcp.tool()
async def interpretar_codigo_resultado(code: str) -> str:
    """Interpret the meaning of a Datafast result code (local lookup, no credentials needed).

    REQUIRED PARAMETERS:
      code (str): Datafast result code. Examples: "000.000.000", "800.100.152", "100.400.500".

    RETURNS:
      {"code": str, "descripcion": str, "aprobada": bool, "pendiente": bool, "rechazada": bool}
    """
    approved_patterns = [r"^000\.000\.", r"^000\.100\.1", r"^000\.300\.", r"^000\.400\.0"]
    pending_patterns = [r"^000\.200\.", r"^800\.400\.5"]
    rejected_patterns = [r"^800\.100\.", r"^900\.100\.", r"^800\.200\.", r"^100\.400\.", r"^200\.300\."]

    is_approved = any(re.match(p, code) for p in approved_patterns)
    is_pending = any(re.match(p, code) for p in pending_patterns)
    is_rejected = any(re.match(p, code) for p in rejected_patterns)

    known: dict[str, str] = {
        "000.000.000": "✅ APROBADA — Transacción exitosa.",
        "000.100.112": "✅ APROBADA — Aprobada (pendiente de confirmación batch).",
        "800.100.152": "❌ RECHAZADA — Declinada por el banco (fondos insuficientes u otro motivo).",
        "800.100.162": "❌ RECHAZADA — Declinada por el banco (restricción de la cuenta).",
        "100.400.500": "⚠️ ERROR — Datos inválidos. Verificar que la suma de impuestos coincida con el amount total.",
    }

    if code in known:
        descripcion = known[code]
    elif is_approved:
        descripcion = "✅ APROBADA según el patrón del código."
    elif is_pending:
        descripcion = "⏳ PENDIENTE — La transacción está en proceso."
    elif is_rejected:
        descripcion = "❌ RECHAZADA según el patrón del código."
    else:
        descripcion = "❓ DESCONOCIDO — Consultar documentación de ACI Worldwide."

    return json.dumps({"code": code, "descripcion": descripcion,
        "aprobada": is_approved, "pendiente": is_pending, "rechazada": is_rejected},
        ensure_ascii=False)
